Breadth-Frist search algorithm
Oliveshark/Pathworks pull request #34
Opened 2020-10-05 20:11 UTC by SharikTLT

Worked, but still need optimize pathFinding API

2020-10-05 20:20 UTC, SharikTLT commented
I think Grid should provide easy way to work with cells, find neighborhood, add debug info for cells, place way point or draw path line. 

May be animate path finding process step by step with animation speed control. It`s looks great at http://qiao.github.io/PathFinding.js/visual/

2020-10-06 07:03 UTC, LiquidityC requested changes

2020-10-06 07:03 UTC, LiquidityC commented on core/src/com/oliveshark/pathworks/framework/grid/Grid.java
> +    public boolean isOutsideGrid(Vector2 pos) {
This can be private can't it?

2020-10-06 09:52 UTC, SharikTLT commented on core/src/com/oliveshark/pathworks/framework/grid/Grid.java
> +    public boolean isOutsideGrid(Vector2 pos) {
It can be private if pathFinder would know about size of grid. I think about two ways:
1) add _getGridSize_ or _getWidth_ and _getHeight_ method. We should also check grid bounds inside pathFinder
2) use _isOutsideGrid_ method

Also I think about pathfinding workflow. May be it reasonable to simplify working with grid by using only grid coordinates and/orc cell neighborhoods.

 For start moving, framework call _pathFind_(Grid, Agent) and receive Waypoints list (founded path to destination). In this solution I check, if agentUserData not contains path, I found it and store inside agentUserData. All others calls of _operate_ method should only process founded waypoint list and moving agent to destination.

I think pathFinder should only work with pathFinding but not moving agent. If we speak about debugging path finding algorithms. 

@LiquidityC , what you think about it?

2020-10-08 06:27 UTC, LiquidityC commented on core/src/com/oliveshark/pathworks/framework/grid/Grid.java
> +    public boolean isOutsideGrid(Vector2 pos) {
Yeah, that might be an improvement. I'll merge this one and we'll take it from there. :wink:

2020-10-08 06:27 UTC, merged